

service: sfn-api-ratelimit

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: sns:*
      Resource: arn:aws:sns:us-east-1:335006469695:NewApiRequest.fifo

plugins:
  - serverless-step-functions

functions:
  pollRequestsAndCheckQuotas:
    handler: handler.pollRequestsAndCheckQuotas
  requestIterator:
    handler: handler.requestIterator
  checkNextRequestIteration:
    handler: handler.checkNextRequestIteration
  banklyRequest:
    handler: handler.banklyRequest
  

stepFunctions:
  stateMachines:
    apiRateLimitOrchestrator:
      name: apiRateLimitOrchestrator
      definition:
        StartAt: PollRequestsAndCheckQuotas
        States:
          PollRequestsAndCheckQuotas:
            Type: Task
            Resource:
              Fn::GetAtt: [pollRequestsAndCheckQuotas, Arn]
            ResultPath: "$.requests"
            Next: RequestIterator
          RequestIterator:
            Type: Task
            Resource:
              Fn::GetAtt: [requestIterator, Arn]
            ResultPath: "$.requests"
            Next: CheckNextRequestInteration
          CheckNextRequestInteration:
            Type: Task
            Resource:
              Fn::GetAtt: [checkNextRequestIteration, Arn]
            ResultPath: "$.hasPendingRequests"
            Next: IsRequestListEmpty
          IsRequestListEmpty:
            Type: Choice
            Choices:
              - Variable: $.hasPendingRequests
                BooleanEquals: true
                Next: RequestIterator
            Default: EndRequestBatch
          EndRequestBatch:
            Type: Pass
            Result: "Finalizou batch de requisições"
            ResultPath: "$.done"
            End: true